import Heading from '@/components/Heading'
import Nav from '@/components/Nav'
import Head from 'next/head'

// TODO: pick an image for the home page
import profile2 from '@/public/images/profile2.png'
import profile2alt from '@/public/images/profile2alt.png'

import Image from 'next/image'

import { fraunces, novaMono } from '@/utils/fonts'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sick Beats</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <div className="flex flex-col items-center gap-10 mt-10">
          <Image
            src={profile2alt}
            alt="drawing of cat wearing sunglasses and headphones"
            className="rounded-full w-[250px] h-[250px]"
          />
          <h1 className={`${novaMono.variable} font-mono text-6xl`}>
            Welcome to Sick Beats
          </h1>
          <p className={`${fraunces.variable} font-serif text-2xl`}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, sint!
          </p>
        </div>
      </main>
    </>
  )
}
