import Heading from '@/components/Heading'
import Nav from '@/components/Nav'
import Head from 'next/head'
import profile from '@/public/images/profile.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sick Beats</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Nav />
      <main>
        <Heading
          imageSrc={profile}
          imageH={144}
          imageW={144}
          imageAlt=""
          title="Welcome to Sick Beats"
          details="A blog where I over-analyze my favorite songs"
        />
      </main>
    </>
  )
}
